# =================================================================
# =PROFILE
# =================================================================
spring:
  profiles:
    active:
#       - prod
      ${PROFILE}
  banner:
    location: classpath:/config/banner.txt
