# =================================================================
# =PROFILE
# =================================================================
spring:
  profiles:
    active:
    - ${PROFILE}
  banner:
    location: classpath:/config/banner.txt
