# =================================================================
# =PROFILE
# =================================================================
server:
  port: 8080

spring:
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://209.45.73.29:54320/db_sesyfarma_qas?useSSL=false
    username: sesyfarma
    password: sesyfarma
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: ctucno.indecopi@gmail.com
    password: povalingepfcezbn
    port: 587
    protocol: smtp
    properties:
      mail:
       smtp:
        auth: false
        starttls:
         enable: true

jwt:
  secret: Sistemas27$@pERu2o20crce.Fl
  expiration: 56000000
  
cloudinary:
  name: unsch
  key: 875145843333534
  secret: UHYevQigSce6VQFV_c8rj76O384
