server:
  port: 8080

spring:
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/db_botica?useSSL=false
    username: botica
    password: botica123
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: sesyfarma.botica@gmail.com
    password: wgeglizqhnbtnmtb
    port: 587
    protocol: smtp
    properties:
      mail:
       smtp:
        auth: false
        starttls:
         enable: true

jwt:
  secret: Sistem@s27$@pERu2o20crce.Fl
  expiration: 56000000
  

cloudinary:
  name: unsch
  key: 875145843333534
  secret: UHYevQigSce6VQFV_c8rj76O384
